name: CI

on:
  pull_request: {}
  push:
    branches:
      - gh-lint

env:
  GOPRIVATE: github.com/weaveworks/aws-sdk-go-private

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: weaveworks/eksctl-build:1ef0e418cf0a49932f0496d7b928162b0062e5e3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache go-build and mod
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: ${{ hashFiles('go.sum') }}
      - name: Lint
        run: make lint
